from pathlib import Path
import json
ROOT=Path(r"C:\Users\BRAD\Documents\------\Engineer Station\FNV_GMOD_THUG2")
OUT=ROOT/"build/prepared/regression_test_packs"
OUT.mkdir(parents=True,exist_ok=True)
packs=[
{"id":"baseline_fallout","title":"Baseline Fallout regression","sidecars":[],"steps":["Run support_playtest_preflight.ps1 with label baseline_fallout.","Boot Fallout New Vegas to main menu.","Load a disposable known-good save.","Move, aim, attack, open/close Pip-Boy and change normal Fallout equipment.","Create a new test save, return to menu, reload it.","Exit normally and run support_playtest_postflight.ps1."],"pass":["No new crash","Normal Fallout controls/inventory work","Save and reload work","No unexpected plugin/DLL/ESP hash change"]},
{"id":"inventory_presentation","title":"GMod/THUG2 inventory presentation","sidecars":[],"steps":["Run preflight with label inventory_presentation.","Inspect representative GMod weapons and THUG2 Skateboard in Pip-Boy.","Verify names and GMod/THUG2 origin icons.","Drop, inspect world model, pick up, container-transfer and trade representative items.","Exit and capture postflight."],"pass":["Correct source-origin icons","Representative items drop/pick up normally","No invisible world item in tested set","No new crash"]},
{"id":"rpg_presentation_fix","title":"RPG presentation sidecar","sidecars":["REM_WeaponPresentation_Fixes.esp"],"steps":["Enable only REM_WeaponPresentation_Fixes.esp after baseline succeeds.","Run preflight with label rpg_presentation_fix.","Inspect GMod RPG Pip-Boy icon and equipped/dropped world presentation.","Drop and pick up the RPG.","Exit, postflight, then disable the sidecar."],"pass":["GMod origin icon appears","Prepared rocket-launcher world model appears","Drop/pickup remains functional","No new crash"]},
{"id":"gmod_prop_catalog","title":"Curated GMod prop sidecar","sidecars":["REM_GModProps_Catalog.esp"],"steps":["Enable only REM_GModProps_Catalog.esp after baseline succeeds.","Run preflight with label gmod_prop_catalog.","Spawn a small sample from every prepared category, not all records at once.","Inspect scale, materials, collision and stability on approach/contact.","For authored movable examples, check ordinary physical response.","Exit, capture postflight, disable sidecar."],"pass":["Sample records resolve","Textures/materials display","Collision is present","Scale is plausible","No crash on spawn/contact"]},
{"id":"combine_armor","title":"Combine Soldier armor sidecar","sidecars":["REM_CombineArmor_Test.esp"],"steps":["Enable only REM_CombineArmor_Test.esp after baseline succeeds.","Run preflight with label combine_armor.","Equip on player; inspect front/back/side in idle, walk, run, crouch and jump.","Check common weapon poses, first person and third person.","Drop armor and inspect world model.","Equip on one test NPC.","Save with armor equipped, reload, then unequip.","Exit, postflight, disable sidecar."],"pass":["No severe clipping/body disappearance","World model works","NPC equip works","Save/load persists","Unequip restores normal body"]},
{"id":"skateboard_baseline","title":"Skateboard non-runtime presentation baseline","sidecars":[],"steps":["Run preflight with label skateboard_baseline.","Equip THUG2 Skateboard without entering skate mode.","Inspect held/world visibility, origin icon, drop and pickup.","Do not use this pack to claim skate-mode mechanics correctness.","Exit and capture postflight."],"pass":["Board is visible in tested inventory/world states","Drop/pickup works","Normal Fallout remains functional before skate-mode activation"]},
{"id":"astra_skate_activation","title":"Astra skate activation gate","sidecars":[],"astra_owned":True,"steps":["Run only on the explicitly assigned Astra build/branch.","Capture preflight and exact DLL/ESP hashes.","Enter skate mode, remain active beyond retarget delay, move/turn/jump, then exit.","Capture plugin log and Windows events immediately after.","Repeat enter/exit at least three times only after first pass survives."],"pass":["No activation crash","No delayed retarget crash","Exit restores Fallout","Repeated transition survives"]},
{"id":"astra_qmenu_tool_physgun","title":"Astra GMod runtime gate","sidecars":[],"astra_owned":True,"steps":["Run only after real GMod Q-menu compatibility runtime is integrated.","Open Q, browse/search curated catalog, select Remover/Duplicator.","Confirm selected Q-menu tool drives Tool Gun with no Fallout selection prompts.","Check GMod notification feedback.","Test Physgun target/hold/rotate/freeze/drop/launch behavior against source semantics.","Exit Q and verify normal Fallout input restores."],"pass":["Real Q-menu flow works","No Fallout tool-selection prompts","Tool Gun follows selected tool","Physgun core behavior stable","Input restores"]}
]
result={"purpose":"Repeatable regression/playtest packs; human execution is required for gameplay assertions.","pack_count":len(packs),"packs":packs}
(OUT/"manifest.json").write_text(json.dumps(result,indent=2),encoding="utf-8")
md=["# Regression Test Packs","","Run preflight before and postflight after every gameplay test. Static validation is not a substitute for these packs.",""]
for p in packs:
    md += ["## "+p["title"],"ID: "+p["id"],"Astra-owned: "+str(bool(p.get("astra_owned"))),"","Steps"]
    md += [str(i+1)+". "+x for i,x in enumerate(p["steps"])]
    md += ["","Pass gates"]+["- "+x for x in p["pass"]]+[""]
(OUT/"REGRESSION_PACKS.md").write_text("\n".join(md)+"\n",encoding="utf-8")
print(json.dumps({"pack_count":len(packs),"ids":[p["id"] for p in packs]},indent=2))